baseurl: "https://strobo.fm"
title: "#strobofm"
footnotereturnlinkcontents: "â†©"
contentdir: "content"
layoutdir: "layout"
staticdir: "static"
publishdir: "public"
uglyURLs: false
metaDataFormat: "yaml"
languageCode: "ja"
permalinks:
  post: "/:title"
taxonomies:
  people: "people"
params:
  StaticURL: "https://strobofm.netlify.app"
